CREATE TABLE IF NOT EXISTS users (
        user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        login varchar NOT NULL,
        name varchar,
        email varchar NOT NULL,
        birth_date date
);

CREATE TABLE IF NOT EXISTS user_friends (
        user_id INTEGER PRIMARY KEY REFERENCES users(user_id),
        friend_id INTEGER REFERENCES users(user_id)
);